# Generated by Django 5.0.6 on 2024-06-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
