# Generated by Django 5.0.6 on 2024-06-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_user_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='place',
        ),
    ]
